# Generated by Django 6.0.6 on 2026-06-23 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('Long Term', 'Long Term'), ('Short Term', 'Short Term')], default='Long Term', max_length=20)),
                ('goal_category', models.CharField(choices=[('Career', 'Career'), ('JEE', 'JEE'), ('NEET', 'NEET'), ('Government Exam', 'Government Exam'), ('Skill Learning', 'Skill Learning'), ('Fitness', 'Fitness'), ('Custom', 'Custom')], default='Custom', max_length=50)),
                ('target_date', models.DateField()),
                ('daily_hours', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Draft', max_length=20)),
                ('success_probability', models.PositiveIntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_days', models.PositiveIntegerField(default=7)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='goals.goal')),
            ],
        ),
    ]
